# Generated by Django 4.2.7 on 2023-11-02 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('ISBN', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=65)),
                ('PublishDate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('Publisher', models.CharField(blank=True, max_length=20, null=True)),
                ('Description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryNames',
            fields=[
                ('CategoryID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('AccID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ElevatorID', models.CharField(max_length=8)),
                ('Floor', models.PositiveSmallIntegerField()),
                ('Wait', models.TimeField()),
            ],
            options={
                'unique_together': {('ElevatorID', 'Floor')},
            },
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Floor', models.PositiveSmallIntegerField()),
                ('Shelf1', models.PositiveSmallIntegerField()),
                ('Shelf2', models.PositiveSmallIntegerField()),
                ('Dist', models.FloatField()),
            ],
            options={
                'unique_together': {('Shelf1', 'Shelf2')},
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('DecimalCode', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('Status', models.SmallIntegerField()),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_project.bookdata')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Out', models.DateTimeField()),
                ('Due', models.DateField()),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_project.book')),
                ('Patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_project.patron')),
            ],
            options={
                'unique_together': {('Patron', 'Book')},
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_project.categorynames')),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_project.bookdata')),
            ],
            options={
                'unique_together': {('CategoryID', 'ISBN')},
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOB', models.DateField()),
                ('Name', models.CharField(max_length=50)),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_project.bookdata')),
            ],
            options={
                'unique_together': {('ISBN', 'DOB')},
            },
        ),
    ]
